// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/schema.proto

package schema

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Struct represents a type specification for dynamic unmarshaling and service orchestration.
//
// Fields:
//   - ClassName: The Go struct type name (also serves as ObjectName for service orchestration)
//   - ServiceName: The service to delegate read/write operations to
//   - Fields: Nested field specifications
type Struct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClassName     string                 `protobuf:"bytes,1,opt,name=ClassName,proto3" json:"ClassName,omitempty"`     // Go struct type name / object identifier
	ServiceName   string                 `protobuf:"bytes,2,opt,name=ServiceName,proto3" json:"ServiceName,omitempty"` // Service name for delegation (read/write operations)
	Fields        map[string]*Value      `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Struct) Reset() {
	*x = Struct{}
	mi := &file_proto_schema_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Struct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Struct) ProtoMessage() {}

func (x *Struct) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schema_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Struct.ProtoReflect.Descriptor instead.
func (*Struct) Descriptor() ([]byte, []int) {
	return file_proto_schema_proto_rawDescGZIP(), []int{0}
}

func (x *Struct) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *Struct) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *Struct) GetFields() map[string]*Value {
	if x != nil {
		return x.Fields
	}
	return nil
}

// Value represents a typed field specification.
// It can be one of four kinds: SingleStruct, ListStruct, MapStruct, or Map2Struct.
type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Value_SingleStruct
	//	*Value_ListStruct
	//	*Value_MapStruct
	//	*Value_Map2Struct
	Kind          isValue_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_proto_schema_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schema_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_proto_schema_proto_rawDescGZIP(), []int{1}
}

func (x *Value) GetKind() isValue_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Value) GetSingleStruct() *Struct {
	if x != nil {
		if x, ok := x.Kind.(*Value_SingleStruct); ok {
			return x.SingleStruct
		}
	}
	return nil
}

func (x *Value) GetListStruct() *ListStruct {
	if x != nil {
		if x, ok := x.Kind.(*Value_ListStruct); ok {
			return x.ListStruct
		}
	}
	return nil
}

func (x *Value) GetMapStruct() *MapStruct {
	if x != nil {
		if x, ok := x.Kind.(*Value_MapStruct); ok {
			return x.MapStruct
		}
	}
	return nil
}

func (x *Value) GetMap2Struct() *Map2Struct {
	if x != nil {
		if x, ok := x.Kind.(*Value_Map2Struct); ok {
			return x.Map2Struct
		}
	}
	return nil
}

type isValue_Kind interface {
	isValue_Kind()
}

type Value_SingleStruct struct {
	SingleStruct *Struct `protobuf:"bytes,1,opt,name=single_struct,json=singleStruct,proto3,oneof"` // Single nested struct
}

type Value_ListStruct struct {
	ListStruct *ListStruct `protobuf:"bytes,2,opt,name=list_struct,json=listStruct,proto3,oneof"` // List/slice of structs
}

type Value_MapStruct struct {
	MapStruct *MapStruct `protobuf:"bytes,3,opt,name=map_struct,json=mapStruct,proto3,oneof"` // Map with string keys
}

type Value_Map2Struct struct {
	Map2Struct *Map2Struct `protobuf:"bytes,4,opt,name=map2_struct,json=map2Struct,proto3,oneof"` // Two-level nested map (map[[2]string]T)
}

func (*Value_SingleStruct) isValue_Kind() {}

func (*Value_ListStruct) isValue_Kind() {}

func (*Value_MapStruct) isValue_Kind() {}

func (*Value_Map2Struct) isValue_Kind() {}

// ListStruct represents a list/slice of Struct specifications.
type ListStruct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListFields    []*Struct              `protobuf:"bytes,1,rep,name=list_fields,json=listFields,proto3" json:"list_fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStruct) Reset() {
	*x = ListStruct{}
	mi := &file_proto_schema_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStruct) ProtoMessage() {}

func (x *ListStruct) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schema_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStruct.ProtoReflect.Descriptor instead.
func (*ListStruct) Descriptor() ([]byte, []int) {
	return file_proto_schema_proto_rawDescGZIP(), []int{2}
}

func (x *ListStruct) GetListFields() []*Struct {
	if x != nil {
		return x.ListFields
	}
	return nil
}

// MapStruct represents a map with string keys to Struct specifications.
type MapStruct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MapFields     map[string]*Struct     `protobuf:"bytes,1,rep,name=map_fields,json=mapFields,proto3" json:"map_fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapStruct) Reset() {
	*x = MapStruct{}
	mi := &file_proto_schema_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapStruct) ProtoMessage() {}

func (x *MapStruct) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schema_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapStruct.ProtoReflect.Descriptor instead.
func (*MapStruct) Descriptor() ([]byte, []int) {
	return file_proto_schema_proto_rawDescGZIP(), []int{3}
}

func (x *MapStruct) GetMapFields() map[string]*Struct {
	if x != nil {
		return x.MapFields
	}
	return nil
}

// Map2Struct represents a two-level nested map structure for map[[2]string]T types.
// The outer map uses the first key, the inner MapStruct uses the second key.
type Map2Struct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Map2Fields    map[string]*MapStruct  `protobuf:"bytes,1,rep,name=map2_fields,json=map2Fields,proto3" json:"map2_fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Map2Struct) Reset() {
	*x = Map2Struct{}
	mi := &file_proto_schema_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Map2Struct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Map2Struct) ProtoMessage() {}

func (x *Map2Struct) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schema_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Map2Struct.ProtoReflect.Descriptor instead.
func (*Map2Struct) Descriptor() ([]byte, []int) {
	return file_proto_schema_proto_rawDescGZIP(), []int{4}
}

func (x *Map2Struct) GetMap2Fields() map[string]*MapStruct {
	if x != nil {
		return x.Map2Fields
	}
	return nil
}

var File_proto_schema_proto protoreflect.FileDescriptor

const file_proto_schema_proto_rawDesc = "" +
	"\n" +
	"\x12proto/schema.proto\x12\x06schema\"\xc6\x01\n" +
	"\x06Struct\x12\x1c\n" +
	"\tClassName\x18\x01 \x01(\tR\tClassName\x12 \n" +
	"\vServiceName\x18\x02 \x01(\tR\vServiceName\x122\n" +
	"\x06fields\x18\x03 \x03(\v2\x1a.schema.Struct.FieldsEntryR\x06fields\x1aH\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.schema.ValueR\x05value:\x028\x01\"\xe8\x01\n" +
	"\x05Value\x125\n" +
	"\rsingle_struct\x18\x01 \x01(\v2\x0e.schema.StructH\x00R\fsingleStruct\x125\n" +
	"\vlist_struct\x18\x02 \x01(\v2\x12.schema.ListStructH\x00R\n" +
	"listStruct\x122\n" +
	"\n" +
	"map_struct\x18\x03 \x01(\v2\x11.schema.MapStructH\x00R\tmapStruct\x125\n" +
	"\vmap2_struct\x18\x04 \x01(\v2\x12.schema.Map2StructH\x00R\n" +
	"map2StructB\x06\n" +
	"\x04kind\"=\n" +
	"\n" +
	"ListStruct\x12/\n" +
	"\vlist_fields\x18\x01 \x03(\v2\x0e.schema.StructR\n" +
	"listFields\"\x9a\x01\n" +
	"\tMapStruct\x12?\n" +
	"\n" +
	"map_fields\x18\x01 \x03(\v2 .schema.MapStruct.MapFieldsEntryR\tmapFields\x1aL\n" +
	"\x0eMapFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12$\n" +
	"\x05value\x18\x02 \x01(\v2\x0e.schema.StructR\x05value:\x028\x01\"\xa3\x01\n" +
	"\n" +
	"Map2Struct\x12C\n" +
	"\vmap2_fields\x18\x01 \x03(\v2\".schema.Map2Struct.Map2FieldsEntryR\n" +
	"map2Fields\x1aP\n" +
	"\x0fMap2FieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.schema.MapStructR\x05value:\x028\x01B\x1bZ\x19github.com/genelet/schemab\x06proto3"

var (
	file_proto_schema_proto_rawDescOnce sync.Once
	file_proto_schema_proto_rawDescData []byte
)

func file_proto_schema_proto_rawDescGZIP() []byte {
	file_proto_schema_proto_rawDescOnce.Do(func() {
		file_proto_schema_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_schema_proto_rawDesc), len(file_proto_schema_proto_rawDesc)))
	})
	return file_proto_schema_proto_rawDescData
}

var file_proto_schema_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_schema_proto_goTypes = []any{
	(*Struct)(nil),     // 0: schema.Struct
	(*Value)(nil),      // 1: schema.Value
	(*ListStruct)(nil), // 2: schema.ListStruct
	(*MapStruct)(nil),  // 3: schema.MapStruct
	(*Map2Struct)(nil), // 4: schema.Map2Struct
	nil,                // 5: schema.Struct.FieldsEntry
	nil,                // 6: schema.MapStruct.MapFieldsEntry
	nil,                // 7: schema.Map2Struct.Map2FieldsEntry
}
var file_proto_schema_proto_depIdxs = []int32{
	5,  // 0: schema.Struct.fields:type_name -> schema.Struct.FieldsEntry
	0,  // 1: schema.Value.single_struct:type_name -> schema.Struct
	2,  // 2: schema.Value.list_struct:type_name -> schema.ListStruct
	3,  // 3: schema.Value.map_struct:type_name -> schema.MapStruct
	4,  // 4: schema.Value.map2_struct:type_name -> schema.Map2Struct
	0,  // 5: schema.ListStruct.list_fields:type_name -> schema.Struct
	6,  // 6: schema.MapStruct.map_fields:type_name -> schema.MapStruct.MapFieldsEntry
	7,  // 7: schema.Map2Struct.map2_fields:type_name -> schema.Map2Struct.Map2FieldsEntry
	1,  // 8: schema.Struct.FieldsEntry.value:type_name -> schema.Value
	0,  // 9: schema.MapStruct.MapFieldsEntry.value:type_name -> schema.Struct
	3,  // 10: schema.Map2Struct.Map2FieldsEntry.value:type_name -> schema.MapStruct
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_schema_proto_init() }
func file_proto_schema_proto_init() {
	if File_proto_schema_proto != nil {
		return
	}
	file_proto_schema_proto_msgTypes[1].OneofWrappers = []any{
		(*Value_SingleStruct)(nil),
		(*Value_ListStruct)(nil),
		(*Value_MapStruct)(nil),
		(*Value_Map2Struct)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_schema_proto_rawDesc), len(file_proto_schema_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_schema_proto_goTypes,
		DependencyIndexes: file_proto_schema_proto_depIdxs,
		MessageInfos:      file_proto_schema_proto_msgTypes,
	}.Build()
	File_proto_schema_proto = out.File
	file_proto_schema_proto_goTypes = nil
	file_proto_schema_proto_depIdxs = nil
}
